language: java
jdk:
  - corretto-17

branches:
  only:
    - main

before_install:
  - unset JAVA_HOME

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'

script: "./gradlew clean build"

notifications:
  email:
    recipients:
      - bjjtachan@gmail.com
